server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_master?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Aa761349852.
  redis:
    ssl: false
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 1000ms
    lettuce:
      shutdown-timeout: 1000ms
      pool:
        min-idle: 4
        max-idle: 8
        max-active: 16
        max-wait: 1000ms
  http:
    session:
      token: session.token
      language: session.lang
    client:
      connection-request-timeout: 10000
      connect-timeout: 10000
      socket-timeout: 20000
      pool-total-max: 256
      pool-route-max: 32