server:
  port: 8080
  tomcat:
    max-threads: 64 #最大执行线程数
    max-connections: 512 #最大请求连接数

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog_master?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: Aa761349852.
    druid:
      enable: true
      min-idle: 8
      max-active: 64
      max-wait-thread-count: 128
      max-wait: 3000
  redis:
    ssl: false
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 1000ms
    lettuce:
      shutdown-timeout: 1000ms
      pool:
        min-idle: 8
        max-idle: 16
        max-active: 64
        max-wait: 1000ms
  http:
    client:
      connection-request-timeout: 10000
      connect-timeout: 10000
      socket-timeout: 20000
      pool-total-max: 128
      pool-route-max: 64